const SOURCES = Object.freeze({
  tseCandidates: {
    id: 'tse-candidates-2026',
    name: 'TSE — Candidatos 2026',
    authority: 'Tribunal Superior Eleitoral',
    kind: 'OFFICIAL',
    cadence: 'Diária, conforme publicação do TSE',
    url: 'https://dadosabertos.tse.jus.br/dataset/candidatos-2026',
    resourceUrl: 'https://cdn.tse.jus.br/estatistica/sead/odsele/consulta_cand/consulta_cand_2026.zip',
    description: 'Registro, situação, cargo, partido e dados declarados das candidaturas de 2026.',
  },
  tseCandidateComplement: {
    id: 'tse-candidates-complement-2026',
    name: 'TSE — Informações complementares 2026',
    authority: 'Tribunal Superior Eleitoral',
    kind: 'OFFICIAL',
    cadence: 'Diária, conforme publicação do TSE',
    url: 'https://dadosabertos.tse.jus.br/dataset/candidatos-2026',
    resourceUrl: 'https://cdn.tse.jus.br/estatistica/sead/odsele/consulta_cand_complementar/consulta_cand_complementar_2026.zip',
    description: 'Situação do julgamento, processo de registro, aceite, limite de gastos e outros campos oficiais.',
    optional: true,
  },
  tseAssets: {
    id: 'tse-assets-2026',
    name: 'TSE — Bens de candidatos 2026',
    authority: 'Tribunal Superior Eleitoral',
    kind: 'OFFICIAL',
    cadence: 'Diária, conforme publicação do TSE',
    url: 'https://dadosabertos.tse.jus.br/dataset/candidatos-2026',
    resourceUrl: 'https://cdn.tse.jus.br/estatistica/sead/odsele/bem_candidato/bem_candidato_2026.zip',
    description: 'Declarações de bens apresentadas pelas pessoas candidatas.',
  },
  tseSocial: {
    id: 'tse-social-2026',
    name: 'TSE — Redes sociais declaradas 2026',
    authority: 'Tribunal Superior Eleitoral',
    kind: 'OFFICIAL',
    cadence: 'Diária, conforme publicação do TSE',
    url: 'https://dadosabertos.tse.jus.br/dataset/candidatos-2026',
    resourceUrl: 'https://cdn.tse.jus.br/estatistica/sead/odsele/consulta_cand/rede_social_candidato_2026.zip',
    description: 'Endereços de redes sociais informados no registro da candidatura.',
  },
  tsePhotos: {
    id: 'tse-photos-2026',
    name: 'TSE — Fotos de candidatos 2026',
    authority: 'Tribunal Superior Eleitoral',
    kind: 'OFFICIAL',
    cadence: 'Diária, conforme publicação do TSE',
    url: 'https://dadosabertos.tse.jus.br/dataset/candidatos-2026',
    archiveUrlTemplate: 'https://cdn.tse.jus.br/estatistica/sead/eleicoes/eleicoes2026/fotos/foto_cand2026_{UF}_div.zip',
    description: 'Retratos oficiais apresentados no registro, associados exclusivamente pelo identificador da candidatura.',
    optional: true,
  },
  tseGovernmentPlans: {
    id: 'tse-government-plans-2026',
    name: 'TSE — Propostas de governo 2026',
    authority: 'Tribunal Superior Eleitoral',
    kind: 'OFFICIAL',
    cadence: 'Diária, conforme publicação do TSE',
    url: 'https://dadosabertos.tse.jus.br/dataset/candidatos-2026',
    archiveUrlTemplate: 'https://cdn.tse.jus.br/estatistica/sead/odsele/proposta_governo/proposta_governo_2026_{UF}.zip',
    description: 'Documentos de propostas de governo entregues por candidaturas aos cargos de governador e presidente.',
    optional: true,
    onDemand: true,
  },
  tseRevenue: {
    id: 'tse-revenue-2026',
    name: 'TSE — Receitas eleitorais 2026',
    authority: 'Tribunal Superior Eleitoral',
    kind: 'OFFICIAL',
    cadence: 'Durante a campanha; recursos podem ser informados em até 72 horas',
    url: 'https://www.tse.jus.br/eleicoes/eleicoes-2026-content/prestacao-de-contas',
    resourceUrl: 'https://cdn.tse.jus.br/estatistica/sead/odsele/prestacao_contas/receitas_candidatos_2026.zip',
    description: 'Receitas de campanha publicadas pela Justiça Eleitoral.',
    optional: true,
  },
  tseExpense: {
    id: 'tse-expense-2026',
    name: 'TSE — Despesas eleitorais 2026',
    authority: 'Tribunal Superior Eleitoral',
    kind: 'OFFICIAL',
    cadence: 'Durante a campanha, conforme entrega das prestações',
    url: 'https://www.tse.jus.br/eleicoes/eleicoes-2026-content/prestacao-de-contas',
    resourceUrl: 'https://cdn.tse.jus.br/estatistica/sead/odsele/prestacao_contas/despesas_candidatos_2026.zip',
    description: 'Despesas de campanha publicadas pela Justiça Eleitoral.',
    optional: true,
  },
  camara: {
    id: 'camara-dados-abertos',
    name: 'Câmara dos Deputados — Dados Abertos',
    authority: 'Câmara dos Deputados',
    kind: 'OFFICIAL',
    cadence: 'Consulta periódica',
    url: 'https://dadosabertos.camara.leg.br/swagger/api.html',
    description: 'Mandatos, despesas, proposições, votações e atividade parlamentar.',
  },
  senado: {
    id: 'senado-dados-abertos',
    name: 'Senado Federal — Dados Abertos',
    authority: 'Senado Federal',
    kind: 'OFFICIAL',
    cadence: 'Consulta periódica',
    url: 'https://legis.senado.leg.br/dadosabertos/api-docs/swagger-ui/index.html',
    description: 'Mandatos, autorias, relatorias, matérias e votações.',
  },
  ibgeBoundaries: {
    id: 'ibge-state-boundaries',
    name: 'IBGE — Malhas territoriais das UFs',
    authority: 'Instituto Brasileiro de Geografia e Estatística',
    kind: 'OFFICIAL',
    cadence: 'Cache de 30 dias; atualização conforme publicação do IBGE',
    url: 'https://www.ibge.gov.br/geociencias/organizacao-do-territorio/malhas-territoriais/15774-malhas.html',
    resourceUrl: 'https://servicodados.ibge.gov.br/api/v3/malhas/paises/BR?intrarregiao=UF&formato=application/vnd.geo+json&qualidade=minima',
    description: 'Limites estaduais usados no próprio navegador para converter uma localização consentida em UF.',
    onDemand: true,
  },
  tcu: {
    id: 'tcu-contas-irregulares',
    name: 'TCU — Contas irregulares, sanções e impedimentos',
    authority: 'Tribunal de Contas da União',
    kind: 'OFFICIAL',
    cadence: 'Diária',
    url: 'https://sites.tcu.gov.br/dados-abertos/webservices-tcu/',
    description: 'Contas julgadas irregulares, possível implicação eleitoral, inabilitação e inidoneidade, consultadas por identificador oficial exato.',
    onDemand: true,
  },
  cgu: {
    id: 'cgu-transparencia',
    name: 'CGU — Portal da Transparência',
    authority: 'Controladoria-Geral da União',
    kind: 'OFFICIAL',
    cadence: 'Diária',
    url: 'https://portaldatransparencia.gov.br/api-de-dados/',
    description: 'Sanções administrativas em CEIS, CNEP e CEAF, consultadas por identificador oficial exato.',
    onDemand: true,
    requiresCredential: true,
  },
  cnj: {
    id: 'cnj-datajud',
    name: 'CNJ — DataJud',
    authority: 'Conselho Nacional de Justiça',
    kind: 'OFFICIAL',
    cadence: 'Conforme atualização dos tribunais',
    url: 'https://www.cnj.jus.br/sistemas/datajud/api-publica/',
    description: 'Metadados de processos públicos. Correspondências exigem identificação inequívoca e revisão.',
    planned: true,
    requiresReview: true,
  },
  factCheck: {
    id: 'google-fact-check',
    name: 'Google Fact Check Tools',
    authority: 'Publicadores de checagens indexados pelo Google',
    kind: 'SECONDARY',
    cadence: 'Consulta periódica',
    url: 'https://developers.google.com/fact-check/tools/api/reference/rest',
    description: 'Localização de alegações já analisadas por organizações de checagem.',
    planned: true,
    requiresCredential: true,
  },
});

function publicSources(statuses = {}) {
  return Object.values(SOURCES).map(({ resourceUrl, archiveUrlTemplate, ...source }) => ({
    ...source,
    status: statuses[source.id] || {
      state: source.planned ? 'PLANNED' : source.onDemand ? 'OK' : 'NOT_SYNCED',
      message: source.planned
        ? 'Conector preparado para uma etapa posterior.'
        : source.onDemand
          ? 'Consulta oficial sob demanda ativa, com cache técnico.'
          : 'Aguardando primeira sincronização.',
    },
  }));
}

module.exports = { SOURCES, publicSources };
